# Spring properties
spring:
  application:
      name: EurekaClient
  servlet:
      context-path: /Rays
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/SCMP
      username: root
      password: root
  jpa:
      generate-ddl : true
      show-sql: true
      properties:
         hibernate:
            format_sql: true
            show-sql: true
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQLDialect

# Discovery Server Access
eureka:
  instance:
    preferIpAddress: true
    # See blog post for details, modify /etc/hosts
    hostname: ncs.in
    appname: client
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
    registerWithEureka: true
    fetchRegistry: true

# HTTP Server
server:
  port: 9098   # HTTP (Tomcat) port